include(${CMAKE_CURRENT_LIST_DIR}/MultiplyMatrix/sources.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/Transpose/sources.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/InverseMatrix/sources.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/LU_inverse/sources.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/sharma/sources.cmake)
